plugins {
    id 'java-library'
}

dependencies {
    api('com.fasterxml.jackson.core:jackson-core:2.15.2')
    api(project(':holy-core-api'))

    api('de.skydb.updater:Updater-Bukkit:0.0.3-SNAPSHOT')

    compileOnly(project(':bukkit-markupapi'))

    compileOnly("org.spigotmc:spigot:$spigotVersion")
    compileOnly("org.spigotmc:spigot-api:$spigotVersion")

    compileOnly("de.dytanic.cloudnet:cloudnet-bridge:$cloudnetVersion")
    compileOnly("de.dytanic.cloudnet:cloudnet-wrapper-jvm:$cloudnetVersion")

    compileOnly("com.gmail.filoghost.holographicdisplays:holographicdisplays-api:$holographicDisplaysVersion")
    compileOnly("com.comphenix.protocol:ProtocolLib:$protocolLibVersion")
}

shadowJar {
    relocate('de.skydb.updater', 'de.teamholy.core.bukkit.updater')
}
