dependencies {
    compileOnly(libs.spigot.full) {
        artifact {
            name = 'spigot-1.8.8'
            classifier = 'dev'
            extension = 'jar'
            type = 'jar'
        }
    }

    implementation(libs.en2do)
    implementation(libs.redisson)
    implementation(libs.jetbrains.annotations)

    compileOnly(libs.cloudnet.bridge)
    compileOnly(libs.cloudnet.wrapper.jvm)
    compileOnly(libs.holographicdisplays.api)

    compileOnly(libs.protocollib.comphenix)
    implementation(libs.jackson.core)

    implementation(project(':holy-core-api'))
    compileOnly(project(':bukkit-markupapi'))
}
