import java.text.SimpleDateFormat

plugins {
    id 'java'
    id('com.gradleup.shadow') version('8.3.5')
    id('net.kyori.blossom') version('1.2.0')
}

def HolyRepoUser = project.findProperty("HolyRepoUser")
def HolyRepoPass = project.findProperty("HolyRepoPass")

subprojects {
    apply plugin: 'java'
    apply plugin: 'com.gradleup.shadow'
    apply plugin: 'net.kyori.blossom'
    apply plugin: 'maven-publish'

    group("$projectGroup")
    version("$projectVersion")

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name('paper-repo')
            url('https://papermc.io/repo/repository/maven-public/')
        }
        maven {
            name('cloudnet-repo')
            url 'https://repo.cloudnetservice.eu/repository/releases/'
        }
        maven {
            name('spigot-repo')
            url('https://hub.spigotmc.org/nexus/content/repositories/snapshots')
        }
        maven {
            name('sonatype-repo')
            url('https://oss.sonatype.org/content/repositories/snapshots')
        }
        maven {
            name('dmulloy2-repo')
            url('https://repo.dmulloy2.net/repository/public/')
        }
        maven {
            name('jitpack-repo')
            url('https://jitpack.io/')
        }
        maven {
            name('codemc-repo')
            url('https://repo.codemc.io/repository/maven-public/')
        }
        maven {
            name('glaremaster-repo')
            url('https://repo.glaremasters.me/repository/public/')
        }
        maven {
            name('skydb-repo')
            url('https://repository.skydb.de/repo')
        }
    }

    // You need to set the project sdk to java 21.
    // gradle compiles the project to java 17 anyway.
    shadowJar {
        relocate('de.skydb.translateapi.bindings', 'de.teamholy.core.translation')
    }

    dependencies {
        implementation("de.skydb.translationapi:TranslateAPI-Bindings:$translationBindingsVersion")

        // Eliminate some boilerplate
        compileOnly("org.projectlombok:lombok:$lombokVersion")
        annotationProcessor("org.projectlombok:lombok:$lombokVersion")
    }

    compileJava.options.encoding = 'UTF-8'
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        toolchain.languageVersion.set(JavaLanguageVersion.of(17))
    }

    // Move all plugins to one "output/" directory in the project directory
    tasks.register('movePlugin', Copy) {
        var outputDir = rootProject.projectDir.getAbsolutePath() + "/output/"
        var targetName = project.name + "-$projectVersion-all.jar"
        // Delete previous build jar
        delete(outputDir + targetName)

        // Copy current build jar
        from('build/libs/')
        into(outputDir)

        include(targetName)
    }
    shadowJar.finalizedBy(movePlugin)

    blossom {
        replaceToken('PROJECT_TIME_FORMAT', new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(new Date()))
        replaceToken('PROJECT_TIME_MILLIS', String.valueOf(System.currentTimeMillis()))
        replaceToken('PROJECT_COMMIT', 'git rev-parse --verify --short HEAD'.execute().text.trim())
        replaceToken('PROJECT_COMMIT_COUNT', 'git rev-list --count HEAD'.execute().text.trim())
        replaceToken('PROJECT_BRANCH', 'git rev-parse --abbrev-ref HEAD'.execute().text.trim())
        replaceToken('PROJECT_SEC_OF_DAY', Calendar.getInstance().getTime().toLocalTime().toSecondOfDay())
        replaceToken('PROJECT_OS', "${System.properties['os.name']}/${System.properties['os.arch']}")
        replaceToken('PROJECT_GRADLE', "$gradle.gradleVersion")
        replaceToken('PROJECT_VERSION', "$projectVersion")
    }

    publishing {
        publications {
            normalJar(MavenPublication) {
                from components.java

                groupId = project.group
                artifactId = project.name
                version = project.version
            }
        }
        repositories {
            maven {
                url = uri("https://repo.gin1.cc/repository/releases/")
                credentials {
                    username = HolyRepoUser
                    password = HolyRepoPass
                }
            }
        }
    }

    tasks.named("publish") {
        dependsOn("jar")
    }
}