import java.text.SimpleDateFormat

plugins {
    id 'java'
    alias(libs.plugins.gradleup.shadow)
    alias(libs.plugins.kyori.blossom)
}

def HolyRepoUser = project.findProperty("HolyRepoUser")
def HolyRepoPass = project.findProperty("HolyRepoPass")

subprojects {
    apply plugin: 'java'
    apply plugin: libs.plugins.gradleup.shadow.get().pluginId
    apply plugin: libs.plugins.kyori.blossom.get().pluginId
    apply plugin: 'maven-publish'

    group("$projectGroup")
    version("$projectVersion")

    repositories {
        mavenLocal()
        mavenCentral()

        maven {
            name = 'cloudnet-releases'
            url = uri('https://repo.cloudnetservice.eu/releases/')
            metadataSources { gradleMetadata(); mavenPom(); artifact() }
            content {
                includeGroup 'de.dytanic.cloudnet'
                includeGroup 'eu.cloudnetservice'
            }
        }
        maven {
            name = 'mvnrepository';
            url = uri('https://mvn.lumine.io/repository/maven-public/');
            content {
                includeGroup 'org.spigotmc'
                includeGroup 'com.comphenix'
            }
        }

        maven {
            name = 'carmrepository';
            url = uri('https://repo.carm.cc/repository/maven-public/');
            content {
                includeGroup 'com.comphenix.protocol';
                includeGroup 'com.mojang';
            }
        }
        maven {
            name = 'spigot-repo'
            url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots')
            content {
                includeGroup 'org.spigotmc'
            }
        }
        maven {
            name = 'paper-repo'
            url = uri('https://papermc.io/repo/repository/maven-public/')
            content {
                includeGroup 'io.papermc.paper'
                includeGroup 'com.destroystokyo.paper'
            }
        }
        maven {
            name = 'dmulloy2-repo'
            url = uri('https://repo.dmulloy2.net/repository/public/')
            content {
                includeGroup 'com.comphenix';
            }
        }
        maven {
            name = 'jitpack-repo';
            url = uri('https://jitpack.io/');
            content {
                includeGroupByRegex 'com\\.github\\..+'
            }
        }
        maven {
            name = 'codemc-repo';
            url = uri('https://repo.codemc.io/repository/maven-public/');
            content {
                includeGroup 'com.gmail.filoghost.holographicdisplays'
            }
        }
        maven {
            name = 'glaremaster-repo';
            url = uri('https://repo.glaremasters.me/repository/public/');
            content {
                includeGroupByRegex 'me\\.glaremasters(\\..+)?'
            }
        }
        maven {
            name = 'skydb-repo';
            url = uri('https://repository.skydb.de/repo');
            content {
                includeGroup 'de.skydb.updater';
                includeGroup 'de.skydb.translationapi'
            }
        }
        maven {
            name = 'sonatype-repo';
            url = uri('https://oss.sonatype.org/content/repositories/snapshots');
            content {
                includeGroupByRegex '.*'
            }
        }

    }

    shadowJar {
        relocate 'de.skydb.translateapi.bindings', 'de.teamholy.core.translation'
        
        doLast {
            def outputDir = rootProject.file("output")
            copy {
                from archiveFile
                into outputDir
            }
            println "Nya~ Copied shiny plugin ${archiveFile.get().asFile.name} to output folder! UwU"
        }
    }

    dependencies {
        implementation libs.translation.bindings
        compileOnly libs.lombok
        annotationProcessor libs.lombok
    }

    compileJava.options.encoding = 'UTF-8'
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        toolchain.languageVersion.set(JavaLanguageVersion.of(17))
    }

    blossom {
        replaceToken 'PROJECT_TIME_FORMAT', new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(new Date())
        replaceToken 'PROJECT_TIME_MILLIS', String.valueOf(System.currentTimeMillis())
        replaceToken 'PROJECT_COMMIT', 'git rev-parse --verify --short HEAD'.execute().text.trim()
        replaceToken 'PROJECT_COMMIT_COUNT', 'git rev-list --count HEAD'.execute().text.trim()
        replaceToken 'PROJECT_BRANCH', 'git rev-parse --abbrev-ref HEAD'.execute().text.trim()
        replaceToken 'PROJECT_SEC_OF_DAY', Calendar.getInstance().getTime().toLocalTime().toSecondOfDay()
        replaceToken 'PROJECT_OS', "${System.properties['os.name']}/${System.properties['os.arch']}"
        replaceToken 'PROJECT_GRADLE', "$gradle.gradleVersion"
        replaceToken 'PROJECT_VERSION', "$projectVersion"
    }

    publishing {
        publications {
            normalJar(MavenPublication) {
                from components.java
                groupId = project.group
                artifactId = project.name
                version = project.version
            }
        }
        repositories {
            maven {
                url = uri("https://repo.gin1.cc/repository/releases/")
                credentials {
                    username = HolyRepoUser
                    password = HolyRepoPass
                }
            }
        }
    }

    tasks.named("publish") {
        dependsOn("jar")
    }
}