dependencies {
    implementation("eu.koboo:en2do:$en2doVersion")
    implementation("org.redisson:redisson:$redissonVersion")
    implementation("org.jetbrains:annotations:$jetbrainsAnnotationsVersion")

    implementation("de.dytanic.cloudnet:cloudnet-bridge:3.4.0-RELEASE")
    implementation("de.dytanic.cloudnet:cloudnet-wrapper-jvm:3.4.0-RELEASE")
    implementation("com.github.Koboo:file-config:-SNAPSHOT");
}