dependencies {
    implementation(libs.en2do)
    implementation(libs.redisson)
    implementation(libs.jetbrains.annotations)
    implementation(libs.mongodb.bson)
    implementation(libs.rabbitmq.client)

    compileOnly(libs.cloudnet.bridge)
    compileOnly(libs.cloudnet.wrapper.jvm)
    implementation(libs.yamlbeans)
}