dependencies {
    implementation(libs.en2do)
    implementation(libs.redisson)
    implementation(libs.jedis)
    implementation(libs.jetbrains.annotations)
    implementation(libs.rabbitmq.client)
    compileOnly(libs.cloudnet.bridge)
    compileOnly(libs.cloudnet.wrapper.jvm)
    compileOnly(libs.bungeecord.api)
    compileOnly(libs.luckperms)
    compileOnly(libs.spigot.api)
    compileOnly(libs.translation.api)
    compileOnly(libs.velocity.api)

    // Add trove4j to provide gnu.trove.map.TObjectIntMap and related classes
    implementation(libs.trove4j)

    implementation(project(':holy-core-api'))
}