dependencies {
    implementation("eu.koboo:en2do:$en2doVersion")
    implementation("org.redisson:redisson:$redissonVersion")
    implementation("org.jetbrains:annotations:$jetbrainsAnnotationsVersion")

    compileOnly ("de.dytanic.cloudnet:cloudnet:$cloudnetVersion")
    compileOnly ("de.dytanic.cloudnet:cloudnet-bridge:$cloudnetVersion")

    implementation(project(':holy-core-api'))
}