name: bukkit-core
version: PROJECT_VERSION
main: de.teamholy.core.bukkit.BukkitCore
depend: [ ProtocolLib, CloudNet-Bridge ]

commands:
    whitelist:
        aliases: [ wl ]
    reportsgui:
        aliases: [ rgui, reportstaffgui ]
    xyz:
    stopcore:
        aliases: [stopc, stop]
    sudo:
    tpblock:
    gc:
    bcommand:
    location:
    gamemode:
        aliases: [ gm ]
    chatclear:
        aliases: [ cc ]