name: bukkit-core
version: 1.0
main: de.teamholy.core.bukkit.BukkitCore
depend: [ ProtocolLib, CloudNet-Bridge, LuckPerms ]

commands:
    whitelist:
        aliases: [ wl ]
    reportsgui:
        aliases: [ rgui, reportstaffgui ]
    stopcore:
        aliases: [stopc, stop]
    sudo:
    tpblock:
    gc:
    bcommand:
    location:
    gamemode:
        aliases: [ gm ]
    clearchat:
        aliases: [ chatc, clch ]
    buglog: