name: bukkit-core
version: 1.0
main: de.teamholy.core.bukkit.BukkitCore
load: STARTUP
depend: [ ProtocolLib, CloudNet-Bridge ]

commands:
    reportsgui:
        aliases: [ rgui, reportstaffgui ]
    xyz:
    stop:
        aliases: [restart, stopserver]