dependencies {
    // You probably wont shade a plugin into this plugin ;)
    // Furthermore, it takes freakin' ages for jitpack to resolve that,
    // so I just uploaded the 1.0.9 to my reposilite to speed up that crap here. ~Koboo
    compileOnly("ua.nanit:NanoLimboPlugin-bungee:1.0.9")
    //implementation('com.github.bivashy.NanoLimboPlugin:api:1.0.6')

    compileOnly("de.dytanic.cloudnet:cloudnet-bridge:$cloudnetVersion")
    compileOnly("de.dytanic.cloudnet:cloudnet-wrapper-jvm:$cloudnetVersion")
    compileOnly("io.github.waterfallmc:waterfall-api:1.18-R0.1-SNAPSHOT")

    // DO NOT IMPLEMENT ALREADY IMPLEMENTED JARS
    compileOnly(project(':holy-core-api'))
    compileOnly(project(':bungee-core-api'))
    compileOnly("redis.clients:jedis:$jedisVersion")

    // Provided by core-api
    //implementation("eu.koboo:en2do:$en2doVersion")
    //implementation("org.redisson:redisson:$redissonVersion")
    //implementation("org.jetbrains:annotations:$jetbrainsAnnotationsVersion")
}